name: Hello World
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, world!"
      - name: Adicionando algo a mais
        run: date